name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          options: DESKTOP_BUILD=ON

      - name: Test Project
        uses: threeal/ctest-action@main